kind: pipeline
name: default

steps:
  - name: test
    image: node:10.13-apline
    commands:
      - yarn install
      - yarn test
  - name: build
    image: node:10.13-apline
    commands:
      - yarn install
      - yarn build